// This file was generated by the \"svnrev\" utility
// You should not modify it manually, as it may be re-generated.
//
// Revision: 9490
// Date: 2016-03-22
//

#define PWIZ_SOURCE
#include "Version.hpp"
#include <sstream>

#ifdef PWIZ_USER_VERSION_INFO_H // in case you need to add any info version of your own
#include PWIZ_USER_VERSION_INFO_H  // must define PWIZ_USER_VERSION_INFO_H_STR for use below
#endif

namespace pwiz {
namespace msdata {

using std::string;

int Version::Major()                {return 03;}
int Version::Minor()                {return 00;}
int Version::Revision()             {return 9490;}
string Version::LastModified()      {return "2016-03-22";}
string Version::str()               
{
	std::ostringstream v;
	v << Major() << '.' << Minor() << '.' << Revision();
#ifdef PWIZ_USER_VERSION_INFO_H
	v << " (" << PWIZ_USER_VERSION_INFO_H_STR << ")";
#endif
	return v.str();
}
}
}
